repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: sampleblog
    namespace: sample-blog
    chart: ./backend/helm

  - name: cassandra
    namespace: sample-blog
    chart: bitnami/cassandra
    set:
      - name: dbUser.user
        value: cassandra
      - name: dbUser.password
        value: cassandra
    
  - name: sampleblog-frontend
    namespace: sample-blog
    chart: ./frontend/helm
